version: '3.2'

services:
    build:
        image: ubuntu:18.04
        volumes:
            - .:/build
        environment:
            # To build a Renewal version, or a server with a different packet version, simply edit this line
            HERCULES_BUILD_OPTS: --disable-renewal --enable-packetver=20180418
            # To override the default repository being checked out (e.g. to build a fork of Hercules):
            # HERCULES_REPO: https://github.com/HerculesWS/Hercules/
            # To build a different branch from the repository:
            # HERCULES_BRANCH: stable

        command: /build/build-hercules.sh
