version: '3.2'

services:
    game_servers:
        # For testing local builds, simply replace this with the local tag you've given
        # the image, e.g.:
        # image: hercules
        image: florianpiesche/hercules-${HERCULES_SERVER_MODE}-${HERCULES_PACKET_VERSION}
        restart: on-failure
        ports:
            # login server
            - 6900:6900
            # character server
            - 6121:6121
            # map server
            - 5121:5121
        environment:
            MYSQL_SERVER: db
            MYSQL_PORT: 3306
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok
            MYSQL_DATABASE: ragnarok
            INTERSERVER_USER: wisp
            INTERSERVER_PASSWORD: wisp
        volumes:
            - configuration:/hercules/conf/import
            - sql_init:/hercules/sql-files/

    db:
        image: mariadb:10.4
        restart: on-failure
        depends_on:
            - game_servers
        environment:
            MYSQL_ROOT_PASSWORD: hercroot
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok
            MYSQL_DATABASE: ragnarok
            INTERSERVER_USER: wisp
            INTERSERVER_PASSWORD: wisp
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql
            - sql_init:/docker-entrypoint-initdb.d

volumes:
    mysql_data:
    configuration:
    sql_init:
