version: '3.2'

services:
    db:
        image: mariadb:10.4
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: hercroot
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok
            MYSQL_DATABASE: ragnarok
            INTERSERVER_USER: wisp
            INTERSERVER_PASSWORD: wisp
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql
            - ./sql-files/${HERCULES_SERVER_TYPE}:/docker-entrypoint-initdb.d

    game_servers:
        image: hercules
        restart: on-failure
        depends_on:
            - db
        ports:
            # login server
            - 6900:6900
            # character server
            - 6121:6121
            # map server
            - 5121:5121
        volumes:
            - ./distrib/conf:/hercules/conf

volumes:
    mysql_data:
