version: '3.2'

services:
    game_servers:
        image: florianpiesche/hercules-${SERVER_MODE:-classic}-${PACKETVER:-20180418}
        restart: on-failure
        environment:
            MYSQL_USER: ${MYSQL_USER:-ragnarok}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ragnarok}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-ragnarok}
            MYSQL_HOST: ${MYSQL_HOST:-db}
            INTERSERVER_USER: ${INTERSERVER_USER:-wisp}
            INTERSERVER_PASSWORD: ${INTERSERVER_PASSWORD:-wisp}
        ports:
            # login server
            - 6900:6900
            # character server
            - 6121:6121
            # map server
            - 5121:5121
        volumes:
            - configuration:/hercules/conf/import
            - sql_init:/hercules/sql-files/

    db:
        image: mariadb:10.4
        restart: on-failure
        depends_on:
            - game_servers
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-hercroot}
            MYSQL_USER: ${MYSQL_USER:-ragnarok}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ragnarok}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-ragnarok}
            INTERSERVER_USER: ${INTERSERVER_USER:-wisp}
            INTERSERVER_PASSWORD: ${INTERSERVER_PASSWORD:-wisp}
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql
            - sql_init:/docker-entrypoint-initdb.d

volumes:
    mysql_data:
    configuration:
    sql_init:
