name: build-images

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                HERCULES_SERVER_MODE: ["classic", "renewal"]
                HERCULES_PACKET_VERSION: ["20180418", ""]
                ARCH: ["arm32v7", "arm64v8", "amd64"]
            runs-on: ubuntu-latest
            steps:
                - name: Build Hercules
                  uses: actions/checkout@v2
                  # ARCH=${arch} HERCULES_SERVER_MODE=${mode} HERCULES_PACKET_VERSION=${packetver} docker-compose up
                  run: docker-compose up -d

                - name: Build image
                  uses: mr-smithers-excellent/docker-build-push@v3
                  with:
                    image: florianpiesche/hercules-${HERCULES_SERVER_MODE}-${HERCULES_PACKET_VERSION:-default}
                    tag: ${ARCH}
                    registry: docker.io
                    dockerfile: hercules_${HERCULES_SERVER_MODE}_packetver-${HERCULES_PACKET_VERSION}_${ARCH}/Dockerfile
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
