name: build-images

on:
  schedule:
    - cron:  '40 11 * * 2'
  workflow_dispatch:

jobs:
  build-hercules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HERCULES_SERVER_MODE: ["classic", "renewal"]
        HERCULES_PACKET_VERSION: ["20180418", "default"]
        ARCH: ["amd64", "arm32v7", "arm64v8"]

    steps:
      - name: Check out repo
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Check out Hercules repo
        uses: actions/checkout@v2
        with:
          repository: HerculesWS/Hercules
          ref: stable
          path: hercules-src

      - name: Set up QEMU for Docker
        uses: docker/setup-qemu-action@v1

      - name: Build Hercules
        run: docker-compose up
        working-directory: ${{ github.workspace }}
        env:
          ARCH: ${{ matrix.ARCH }}
          HERCULES_SERVER_MODE: ${{ matrix.HERCULES_SERVER_MODE }}
          HERCULES_PACKET_VERSION: ${{ matrix.HERCULES_PACKET_VERSION }}

      - name: Publish Hercules build
        uses: actions/upload-artifact@v2
        with:
          name: hercules-${{ matrix.HERCULES_SERVER_MODE }}-${{ matrix.HERCULES_PACKET_VERSION }}-${{ matrix.ARCH }}
          path: ./distrib

  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HERCULES_SERVER_MODE: ["classic", "renewal"]
        HERCULES_PACKET_VERSION: ["20180418", "default"]
    needs: build-hercules

    steps:
      - name: Check out repo
        uses: actions/checkout@v1

      - name: Download amd64 frontend build
        uses: actions/download-artifact@v2
        with:
          name: hercules-${{ matrix.HERCULES_SERVER_MODE }}-${{ matrix.HERCULES_PACKET_VERSION }}-amd64
          path: distrib/linux/amd64

      - name: Download arm32v7 frontend build
        uses: actions/download-artifact@v2
        with:
          name: hercules-${{ matrix.HERCULES_SERVER_MODE }}-${{ matrix.HERCULES_PACKET_VERSION }}-arm32v7
          path: distrib/linux/arm/v7
  
      - name: Download arm64 frontend build
        uses: actions/download-artifact@v2
        with:
          name: hercules-${{ matrix.HERCULES_SERVER_MODE }}-${{ matrix.HERCULES_PACKET_VERSION }}-arm64v8
          path: distrib/linux/arm/64
  
      - name: Set up QEMU for Docker
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            florianpiesche/hercules-${{ matrix.HERCULES_SERVER_MODE }}-${{ matrix.HERCULES_PACKET_VERSION }}
          platforms: linux/amd64,linux/arm/v7,linux/arm/64
