name: build-images

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HERCULES_SERVER_MODE: ["classic", "renewal"]
        HERCULES_PACKET_VERSION: ["20180418", ""]
        PLATFORM: ["linux/amd64", "linux/arm/v7", "linux/arm64"]

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        # ARCH=${arch} HERCULES_SERVER_MODE=${mode} HERCULES_PACKET_VERSION=${packetver} docker-compose up

      - name: Build Hercules
        run: |
          docker-compose up
        env:
          ARCH: ${ matrix.PLATFORM }
          HERCULES_SERVER_MODE: ${ matrix.HERCULES_SERVER_MODE }
          HERCULES_PACKET_VERSION: ${ matrix.HERCULES_PACKET_VERSION }

      - name: Build image
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: florianpiesche/hercules-${ matrix.HERCULES_SERVER_MODE }-${ matrix.HERCULES_PACKET_VERSION:-default }
          tag: ${ matrix.ARCH }
          registry: docker.io
          dockerfile: hercues_distrib/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        env:
          ARCH: ${ matrix.PLATFORM }
          HERCULES_SERVER_MODE: ${ matrix.HERCULES_SERVER_MODE }
          HERCULES_PACKET_VERSION: ${ matrix.HERCULES_PACKET_VERSION }
  