name: build-images

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HERCULES_SERVER_MODE: ["classic", "renewal"]
        HERCULES_PACKET_VERSION: ["20180418", "default"]
        # ARCH: ["amd64", "arm32v7", "arm64v8"]
        ARCH: ["amd64"]

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Build Hercules
        run: ./build-hercules.sh
        working-directory: ${{ github.workspace }}
        env:
          WORKSPACE: ${{ env.GITHUB_WORKSPACE }}
          ARCH: ${{ matrix.ARCH }}
          HERCULES_SERVER_MODE: ${{ matrix.HERCULES_SERVER_MODE }}
          HERCULES_PACKET_VERSION: ${{ matrix.HERCULES_PACKET_VERSION }}

      - name: Build image
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: florianpiesche/hercules-${{ matrix.HERCULES_SERVER_MODE }}-${{ matrix.HERCULES_PACKET_VERSION }}
          tag: ${{ matrix.ARCH }}
          registry: docker.io
          dockerfile: ${{ env.GITHUB_WORKSPACE }}/hercules_distrib/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        env:
          ARCH: ${{ matrix.ARCH }}
          HERCULES_SERVER_MODE: ${{ matrix.HERCULES_SERVER_MODE }}
          HERCULES_PACKET_VERSION: ${{ matrix.HERCULES_PACKET_VERSION }}
  