name: build-images

on:
  schedule:
    - cron:  '40 11 * * 2'
  workflow_dispatch:

jobs:
  build-hercules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HERCULES_SERVER_MODE: ["classic"]
        HERCULES_PACKET_VERSION: ["20180418"]
        # HERCULES_SERVER_MODE: ["classic", "renewal"]
        # HERCULES_PACKET_VERSION: ["20180418", "default"]

    steps:
      - name: Check out repo
        uses: actions/checkout@v1

      - name: Set up QEMU for Docker
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Hercules
        run: docker-compose -f docker-compose-alpine.yml up
        working-directory: ${{ github.workspace }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: |
            florianpiesche/hercules-${{ matrix.HERCULES_SERVER_MODE }}-${{ matrix.HERCULES_PACKET_VERSION }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args:
            - HERCULES_SERVER_MODE=${{ matrix.HERCULES_SERVER_MODE }}
            - HERCULES_PACKET_VERSION=${{ matrix.HERCULES_PACKET_VERSION }}
