name: build-images

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HERCULES_SERVER_MODE: ["classic", "renewal"]
        HERCULES_PACKET_VERSION: ["20180418", "default"]
        ARCH: ["amd64", "arm32v7", "arm64v8"]
        # ARCH: ["amd64"]

    steps:
      - name: Check out repo
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Build Hercules
        run: docker-compose up
        working-directory: ${{ github.workspace }}
        env:
          ARCH: ${{ matrix.ARCH }}
          HERCULES_SERVER_MODE: ${{ matrix.HERCULES_SERVER_MODE }}
          HERCULES_PACKET_VERSION: ${{ matrix.HERCULES_PACKET_VERSION }}

      - name: Build image
        run: docker build . -t florianpiesche/hercules-${{ matrix.HERCULES_SERVER_MODE }}-${{ matrix.HERCULES_PACKET_VERSION }}:${{ matrix.ARCH }} --build-arg ARCH=${{ matrix.ARCH }}
        working-directory: ${{ github.workspace }}/hercules_distrib
