name: build-images

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HERCULES_SERVER_MODE: ["classic", "renewal"]
        HERCULES_PACKET_VERSION: ["20180418", "default"]
        ARCH: ["amd64", "arm32v7", "arm64v8"]
        # ARCH: ["amd64"]

    steps:
      - name: Check out repo
        uses: actions/checkout@v1
        with:
          submodules: recursive
        
      - name: Install QEmu for cross-architecture build support
        run: sudo apt-get install qemu binfmt-support qemu-user-static
      
      - name: Set up Docker to use QEmu
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build Hercules
        run: docker-compose up
        working-directory: ${{ github.workspace }}
        env:
          ARCH: ${{ matrix.ARCH }}
          HERCULES_SERVER_MODE: ${{ matrix.HERCULES_SERVER_MODE }}
          HERCULES_PACKET_VERSION: ${{ matrix.HERCULES_PACKET_VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: florianpiesche/hercules-${{ matrix.HERCULES_SERVER_MODE }}-${{ matrix.HERCULES_PACKET_VERSION }}
          tag_with_ref: true
          tags: ${{ matrix.ARCH }},latest
          build_args: ARCH=${{ matrix.ARCH }}
          path: ${{ github.workspace }}/hercules_distrib
